Repository OWASP/threat-dragon, pull requests merged in 2022-11, with the labels that each got.

#551 add credits page to about section, for Dreamsverse artwork
  docs/assets/images/threatdragonx128.png
  docs/home/about/about.md
  docs/home/about/conduct.md
  docs/home/about/credits.md
  docs/home/about/license.md
Labels: documentation, version-2.0

#552 preparation for desktop save of models
  td.vue/src/components/Graph.vue
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/ImportModel.vue
  td.vue/src/views/MainDashboard.vue
  td.vue/src/views/NewThreatModel.vue
  td.vue/src/views/OauthReturn.vue
  td.vue/src/views/ThreatModel.vue
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/src/views/UpgradeDiagram.vue
  td.vue/src/views/git/BranchAccess.vue
  td.vue/src/views/git/RepositoryAccess.vue
  td.vue/src/views/git/ThreatModelSelect.vue
Labels: version-2.0, chore

#555 Provide diagram description Fix
  td.vue/src/i18n/cn.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/service/demo/demo-threat-model.js
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/src/service/migration/diagram.js
  td.vue/src/views/ThreatModel.vue
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/tests/unit/views/threatmodel.spec.js
  td.vue/tests/unit/views/threatmodelEdit.spec.js
Labels: enhancement, version-2.0
