Repository OWASP/threat-dragon, pull requests merged in 2022-10, with the labels that each got.

#541 Update french translation for v2
  td.vue/src/i18n/fr.js
Labels: enhancement, version-2.0, I18N

#542 Implement dropzone for threat model imports.
  td.vue/src/i18n/en.js
  td.vue/src/views/Import.vue
Labels: enhancement, version-2.0

#544 add in some translation strings for file drag
  td.vue/src/i18n/cn.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/views/ImportModel.vue
Labels: version-2.0, chore

#545 align open-file with drop-file
  td.vue/src/i18n/cn.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/ImportModel.vue
  td.vue/tests/unit/views/importModel.spec.js
Labels: version-2.0, chore

#548 Update cn.js
  td.vue/src/i18n/cn.js
Labels: version-2.0, I18N
