Repository OWASP/threat-dragon, pull requests merged in 2022-08, with the labels that each got.

#466 Eslint update
  README.md
  docs/development/env.md
  docs/usage/install/docker.md
  docs/usage/install/web.md
  td.server/README.md
  td.server/package.json
  td.server/pnpm-lock.yaml
  td.vue/README.md
  td.vue/package.json
  td.vue/pnpm-lock.yaml
Labels: chore

#467 Server logging
  .gitignore
  docs/development/env.md
  td.server/dev.js
  td.server/index.js
  td.server/src/app.js
  td.server/src/config/bearer.config.js
  td.server/src/controllers/auth.js
  td.server/src/controllers/healthcheck.js
  td.server/src/controllers/homecontroller.js
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/env/Env.js
  td.server/src/helpers/encryption.helper.js
  td.server/src/helpers/logger.helper.js
  td.server/src/providers/index.js
  td.server/src/repositories/token.js
  td.server/test/mocks/express.mocks.js
Labels: chore

#473 Rate limiting only for production environments
  docs/README.md
  td.server/src/app.js
Labels: bug

#469 fix: multi-line description
  td.vue/src/components/report/ExecutiveSummary.vue
  td.vue/src/views/ThreatModel.vue
Labels: bug, version-2.0, Priority

#475 revise logging to trace login request
  td.server/dev.js
  td.server/index.js
  td.server/src/config/bearer.config.js
  td.server/src/controllers/auth.js
  td.server/src/controllers/healthcheck.js
  td.server/src/controllers/homecontroller.js
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/helpers/encryption.helper.js
  td.server/src/repositories/token.js
Labels: chore, version-2.x

#474 expand healthz to show uptime
  docs/development/env.md
  docs/development/internationalization.md
  td.server/src/config/routes.config.js
  td.server/src/controllers/healthcheck.js
  td.server/src/controllers/healthz.js
  td.server/src/healthcheck.js
  td.server/test/config/routes.config.spec.js
  td.server/test/controllers/healthcheck.spec.js
Labels: enhancement

#477 development front end bound to port 8080
  CONTRIBUTING.md
  docs/development/testing/e2e.md
  docs/home/about/contributing.md
  package.json
  td.server/package.json
  td.server/src/controllers/auth.js
  td.vue/package.json
Labels: chore, version-2.x

#479 Fix some multi line issues
  td.vue/src/components/printed-report/ExecutiveSummary.vue
  td.vue/src/components/printed-report/ReportEntity.vue
  td.vue/src/components/report/ReportEntity.vue
Labels: reports, version-2.x

#478 no rate-limiting for test environments
  td.server/src/app.js
Labels: chore, version-2.x

#480 always allow logout using GET
  td.server/src/config/routes.config.js
  td.server/src/controllers/auth.js
  td.server/src/controllers/homecontroller.js
  td.server/test/controllers/homecontroller.spec.js
Labels: version-2.0, chore

#482 revert breaking change to homecontroller
  td.server/src/controllers/homecontroller.js
  td.server/test/controllers/homecontroller.spec.js
Labels: bug, blocker

#484 Docs update
  README.md
  docs/development/actions/about.md
  docs/development/api.md
  docs/development/local.md
  docs/development/release-process.md
  docs/home/about/conduct.md
  docs/home/trust/container.md
  docs/home/trust/dast.md
  docs/home/trust/dependencies.md
  docs/home/trust/incidents.md
  docs/home/trust/sast.md
  docs/home/trust/sbom.md
  docs/usage/install/docker.md
  td.server/package.json
  td.server/src/healthcheck.js
  utils/DragonExtractor/README.md
Labels: chore, version-2.x

#489 update docs page for docker build and run
  docs/usage/install/docker.md
Labels: documentation, chore, version-2.x

#490 update for debugging of docker containers
  docs/usage/install/docker.md
Labels: documentation, chore, version-2.x

#486 prepare to test electron desktop
  docs/development/env.md
  package.json
  pnpm-lock.yaml
  td.vue/package.json
  td.vue/pnpm-lock.yaml
  td.vue/src/desktop/desktop.js
  td.vue/src/desktop/desktop.menu.js
  td.vue/tests/unit/desktop/desktop.spec.js
  td.vue/vue.config.js
Labels: version-2.0, chore, desktop

#491 add auto-update for electron app
  td.vue/package.json
  td.vue/pnpm-lock.yaml
  td.vue/src/desktop/desktop.js
Labels: desktop, version-2.x

#488 prepare to add threat engine
  ThreatDragonModels/demo-threat-model/demo-threat-model.json
  ThreatDragonModels/legacy_desktop_model/legacy_desktop_model.json
  ThreatDragonModels/legacy_model/legacy_model.json
  ThreatDragonModels/legacy_model_1/legacy_model_1.json
  ThreatDragonModels/legacy_model_2/legacy_model_2.json
  docs/development/api.md
  docs/development/env.md
  docs/development/local.md
  docs/development/testing/e2e.md
  docs/development/testing/unit.md
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/ThreatEditModal.vue
  td.vue/src/i18n/cn.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/pt.js
  td.vue/src/service/demo/demo-threat-model.js
  td.vue/src/service/demo/legacy-desktop-model.js
  td.vue/src/service/demo/legacy-model-2.js
  td.vue/src/service/demo/legacy-model.js
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/src/service/migration/diagram.js
  td.vue/src/service/threats/index.js
  td.vue/src/service/threats/models/cia.js
  td.vue/src/service/threats/models/linddun.js
  td.vue/src/service/threats/models/stride.js
  td.vue/src/service/x6/factory.js
  td.vue/src/service/x6/stencil.js
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/tests/unit/service/threats/index.spec.js
  td.vue/tests/unit/service/threats/models/index.spec.js
  td.vue/tests/unit/service/x6/stencil.spec.js
  utils/threat-mvp/td_json/first_tm.json
  utils/threat-mvp/td_json/test1.json
Labels: enhancement, version-2.0, theat engine

#494 Diagram type handling
  ThreatDragonModels/legacy_model_1/legacy_model_1.json
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/ThreatEditModal.vue
  td.vue/src/i18n/en.js
  td.vue/src/i18n/fr.js
  td.vue/src/service/demo/legacy-model-2.js
  td.vue/src/service/migration/diagram.js
  td.vue/src/service/threats/index.js
  td.vue/src/views/ThreatModel.vue
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/tests/unit/components/graphMeta.spec.js
  td.vue/tests/unit/components/threatEditModal.spec.js
  td.vue/tests/unit/service/threats/index.spec.js
Labels: version-2.x

#499 schema uses tdVersion
  td.server/test/controllers/threatmodelcontroller.spec.js
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/src/service/migration/diagram.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/NewThreatModel.vue
  td.vue/tests/e2e/specs/data/demo.js
  td.vue/tests/unit/service/migration/diagram.spec.js
  td.vue/tests/unit/store/modules/threatmodel.spec.js
Labels: chore, version-2.x

#498 Threat engine applies threat by element
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/ThreatEditModal.vue
  td.vue/src/i18n/en.js
  td.vue/src/service/threats/index.js
  td.vue/src/service/threats/models/index.js
  td.vue/src/service/threats/models/linddun.js
  td.vue/src/service/threats/models/stride.js
  td.vue/tests/unit/components/threatEditModal.spec.js
  td.vue/tests/unit/service/threats/index.spec.js
  td.vue/tests/unit/service/threats/models/index.spec.js
  td.vue/tests/unit/service/threats/models/linddun.spec.js
  td.vue/tests/unit/service/threats/models/stride.spec.js
Labels: theat engine, version-2.x

#500 add clean for root and td.vue directories
  README.md
  package.json
  td.server/README.md
  td.server/package.json
  td.vue/.gitignore
  td.vue/README.md
  td.vue/package.json
  td.vue/pnpm-lock.yaml
  td.vue/src/service/threats/models/index.js
Labels: chore, version-2.x

#496 reinstate tests for electron
  .dockerignore
  package.json
  td.server/test/app.spec.js
  td.server/test/config/env.config.spec.js
  td.server/test/config/parsers.config.spec.js
  td.server/test/config/routes.config.spec.js
  td.server/test/controllers/homecontroller.spec.js
  td.server/test/controllers/threatmodelcontroller.spec.js
  td.server/test/helpers/encryption.helper.spec.js
  td.server/test/repositories/threatmodelrepository.spec.js
  td.vue/.gitignore
  td.vue/package.json
  td.vue/pnpm-lock.yaml
  td.vue/src/desktop/desktop.menu.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/fr.js
  td.vue/tests/e2e/desktop/desktop.spec.js
  td.vue/tests/unit/desktop/desktop.menu.spec.js
  td.vue/tests/unit/desktop/desktop.spec.js
  td.vue/tests/unit/router/index.spec.js
  td.vue/tests/unit/service/threats/index.spec.js
  td.vue/vue.config.js
  td.vue/wdio.config.js
Labels: desktop, version-2.x

#502 temporary remove search feature for diagram elements
  td.vue/src/service/x6/stencil.js
  td.vue/tests/unit/service/x6/stencil.spec.js
  td.vue/vue.config.js
Labels: version-2.x
