Repository OWASP/threat-dragon, pull requests merged in 2022-05, with the labels that each got.

#427 navbar height increased by 10
  td.vue/src/components/Navbar.vue
Labels: enhancement, version-2.0, version-2.x

#430 update version of electron
  pnpm-lock.yaml
  td.server/pnpm-lock.yaml
  td.vue/package.json
  td.vue/pnpm-lock.yaml
  td.vue/src/components/Navbar.vue
  td.vue/src/store/index.js
Labels: chore

#432 move to node 18 for github workflows
  .github/workflows/browserstack.yaml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
Labels: chore

#433 Fix some typos
  ThreatDragonModels/legacy_desktop_model/legacy_desktop_model.json
Labels: documentation
