Repository OWASP/threat-dragon, pull requests merged in 2023-09, with the labels that each got.

#731 Initial finnish translation.
  td.vue/src/desktop/menu.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/index.js
  td.vue/tests/unit/desktop/menu.spec.js
Labels: I18N, version-2.1

#737 Add GitHub search option/feature for #733
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/env/Github.js
  td.server/src/repositories/threatmodelrepository.js
Labels: enhancement, version-2.1

#742 Diagram style updates
  .gitignore
  ThreatDragonModels/test-reports.json
  ThreatDragonModels/v2-threat-model.json
  td.vue/src/components/GraphProperties.vue
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/src/service/entity/default-properties.js
  td.vue/src/service/migration/diagram.js
  td.vue/src/service/x6/graph/data-changed.js
  td.vue/src/service/x6/graph/events.js
  td.vue/src/service/x6/graph/graph.js
  td.vue/src/service/x6/shapes/actor.js
  td.vue/src/service/x6/shapes/flow-stencil.js
  td.vue/src/service/x6/shapes/flow.js
  td.vue/src/service/x6/shapes/process.js
  td.vue/src/service/x6/shapes/store.js
  td.vue/src/service/x6/shapes/text.js
  td.vue/src/service/x6/shapes/trust-boundary-box.js
  td.vue/src/service/x6/shapes/trust-boundary-curve-stencil.js
  td.vue/src/service/x6/shapes/trust-boundary-curve.js
  td.vue/tests/e2e/fixtures/v2-model.json
  td.vue/tests/unit/components/graphProperties.spec.js
  td.vue/tests/unit/entity/default-properties.spec.js
  td.vue/tests/unit/service/x6/graph/data-changed.spec.js
  td.vue/tests/unit/service/x6/graph/events.spec.js
  td.vue/tests/unit/service/x6/graph/graph.spec.js
Labels: enhancement, version-2.1

#747 update workflow actions to the latest
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  .release-note-template.md
  release-process.md
Labels: chore, automation

#754 over ride systeminformation version and update markdownlint
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  td.server/package-lock.json
  td.server/package.json
  td.vue/browserstack.nightly.json
  td.vue/browserstack.smokes.json
  td.vue/package-lock.json
  td.vue/package.json
Labels: dependencies, automation

#755 fix bug where selecting a threat boundary curve throws an error
  td.vue/src/components/GraphProperties.vue
  td.vue/src/service/x6/graph/data-changed.js
  td.vue/src/service/x6/graph/events.js
  td.vue/src/service/x6/shapes/trust-boundary-curve.js
  td.vue/tests/unit/components/graphProperties.spec.js
  td.vue/tests/unit/service/x6/graph/events.spec.js
Labels: bug, version-2.1
