Repository OWASP/threat-dragon, pull requests merged in 2023-02, with the labels that each got.

#595 Desktop end to end testing
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  .trivyignore
  docs/development/environment.md
  package.json
  td.server/package.json
  td.vue/package.json
  td.vue/pnpm-lock.yaml
  td.vue/public/preload.js
  td.vue/src/desktop/desktop.js
  td.vue/src/desktop/logger.js
  td.vue/src/desktop/menu.js
  td.vue/src/desktop/utils.js
  td.vue/tests/e2e/desktop/desktop.spec.js
  td.vue/tests/unit/desktop/utils.spec.js
  td.vue/vue.config.js
  td.vue/wdio.config.js
Labels: enhancement, version-2.0, desktop

#599 [T/t]hreat dragon -> Threat Dragon
  docs/development/local.md
  docs/home/about/credits.md
  docs/usage/collaboration/linking.md
Labels: documentation, version-2.0

#600 Minor cleanup of doc
  README.md
  docs/home/trust/dast.md
Labels: documentation, version-2.0

#596 Sign installer images on release
  .github/workflows/browserstack.yaml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/release.yaml
  package.json
  td.server/package.json
  td.vue/package.json
  td.vue/vue.config.js
Labels: version-2.0, chore

#601 Report layout fixes
  td.vue/src/components/report/Coversheet.vue
  td.vue/src/views/ReportModel.vue
Labels: bug, version-2.0

#606 Spanish Translations suggested, let me know any concerns
  td.vue/src/i18n/es.js
Labels: version-2.0, I18N

#605 Dashboard actions kept to equal height
  td.vue/src/components/DashboardAction.vue
  td.vue/src/views/MainDashboard.vue
Labels: bug, version-2.0

#608 use electron-updater to check for updates
  td.vue/package.json
  td.vue/pnpm-lock.yaml
  td.vue/src/desktop/desktop.js
Labels: bug, version-2.0, desktop

#609 stop text overwriting cupcake
  td.vue/src/i18n/de.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/views/HomePage.vue
  td.vue/tests/e2e/specs/home.cy.js
Labels: bug, version-2.0

#610 update release pipeline
  .github/workflows/release.yaml
Labels: version-2.0, chore
