Repository OWASP/threat-dragon, pull requests merged in 2023-01, with the labels that each got.

#585 support multiple diagrams
  ThreatDragonModels/v2-new-model.json
  ThreatDragonModels/v2-threat-model.json
  docs/development/example-store.json
  docs/development/schema/owasp.threat-dragon.schema.json
  td.vue/package.json
  td.vue/src/components/Graph.vue
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/service/demo/v2-new-model.js
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/NewThreatModel.vue
  td.vue/src/views/ThreatModel.vue
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/src/views/git/ThreatModelSelect.vue
  td.vue/tests/e2e/fixtures/v2-model.json
  td.vue/tests/e2e/fixtures/v2-new-model.json
  td.vue/tests/unit/components/graph.spec.js
  td.vue/tests/unit/components/threatEditModal.spec.js
Labels: bug, enhancement, version-2.0

#588 fix up for renaming of docs environment page
  README.md
  docs/development/environment.md
  docs/development/local.md
  docs/development/testing/adhoc.md
  docs/home/about/about.md
  docs/home/trust/incidents.md
  docs/usage/install/docker.md
  docs/usage/install/web.md
  td.server/src/env/ThreatDragon.js
  td.server/src/helpers/encryption.helper.js
  td.server/src/providers/index.js
Labels: bug, documentation, blocker, beta

#546 Add support for github enterprise
  example.env
  td.server/src/env/Github.js
  td.server/src/providers/github.js
  td.server/src/repositories/threatmodelrepository.js
  td.server/test/repositories/threatmodelrepository.spec.js
  td.vue/src/views/git/BranchAccess.vue
  td.vue/src/views/git/ThreatModelSelect.vue
Labels: enhancement

#591 implement opening of recent threat model files
  td.vue/src/desktop/desktop.js
  td.vue/src/desktop/menu.js
  td.vue/tests/unit/desktop/menu.spec.js
  td.vue/tests/unit/views/homePage.spec.js
Labels: bug, version-2.0, beta
