Repository OWASP/threat-dragon, pull requests merged in 2023-08, with the labels that each got.

#711 update release process
  .github/workflows/ci.yaml
  .github/workflows/housekeeping.yaml
  .github/workflows/release.yaml
  .release-note-template.md
  package-lock.json
  package.json
  release-process.md
  security.md
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
Labels: bug, automation

#713 I18N: add German translation #524
  td.vue/src/i18n/de.js
Labels: enhancement, I18N

#714 pipeline updates
  README.md
  td.server/src/app.js
Labels: automation

#715 fix MacOS electron builder
  .github/workflows/deploy.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  package-lock.json
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/vue.config.js
  td.vue/wdio.config.js
Labels: bug, automation

#717 move to version 2.0.5
  .github/workflows/release.yaml
  .release-note-template.md
  package-lock.json
  package.json
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/store/modules/auth.js
  td.vue/tests/e2e/specs/login.cy.js
  td.vue/tests/e2e/specs/logout.cy.js
  td.vue/tests/unit/store/modules/auth.spec.js
Labels: chore

#683 Add DIE Model in addition to existing
  .gitignore
  package.json
  td.vue/src/assets/thumbnail.die.jpg
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/service/threats/index.js
  td.vue/src/service/threats/models/die.js
  td.vue/src/service/threats/models/index.js
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/tests/unit/service/threats/index.spec.js
  td.vue/tests/unit/service/threats/models/die.spec.js
  td.vue/tests/unit/service/threats/models/index.spec.js
Labels: enhancement, theat engine, version-2.1

#721 Various improvements for diagrams
  td.vue/package.json
  td.vue/src/components/Graph.vue
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/GraphProperties.vue
  td.vue/src/components/GraphThreats.vue
  td.vue/src/service/x6/graph/graph.js
  td.vue/src/views/ImportModel.vue
  td.vue/tests/unit/components/graphMeta.spec.js
  td.vue/tests/unit/components/graphThreats.spec.js
  td.vue/tests/unit/service/x6/graph/graph.spec.js
Labels: version-2.1
