Repository OWASP/threat-dragon, pull requests merged in 2023-07, with the labels that each got.

#688 add repo select page query param
  td.vue/src/components/SelectionPage.vue
  td.vue/src/service/api/api.js
  td.vue/src/service/api/threatmodelApi.js
  td.vue/src/store/modules/branch.js
  td.vue/src/store/modules/provider.js
  td.vue/src/store/modules/repository.js
  td.vue/src/views/git/BranchAccess.vue
  td.vue/src/views/git/RepositoryAccess.vue
  td.vue/src/views/git/ThreatModelSelect.vue
  td.vue/tests/unit/service/api/api.spec.js
  td.vue/tests/unit/service/api/threatmodelApi.spec.js
  td.vue/tests/unit/store/modules/branch.spec.js
  td.vue/tests/unit/store/modules/provider.spec.js
  td.vue/tests/unit/store/modules/repository.spec.js
  td.vue/tests/unit/views/branchAccess.spec.js
  td.vue/tests/unit/views/repositoryAccess.spec.js
Labels: bug, version-2.1

#693 Add await to provider selection call
  td.vue/src/components/ProviderLoginButton.vue
Labels: bug, version-2.1

#700 diagrams added on individual rows
  td.vue/src/views/ThreatModelEdit.vue
Labels: bug

#664 update reports
  .github/workflows/.zap-rules-web.tsv
  .gitignore
  release-process.md
  td.vue/src/components/report/Coversheet.vue
  td.vue/src/components/report/DiagramDetail.vue
  td.vue/src/desktop/menu.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/views/ReportModel.vue
  td.vue/tests/e2e/specs/threatmodel/report.cy.js
  td.vue/tests/unit/components/report/diagramDetail.spec.js
Labels: bug, reports

#706 add desktop as an access provider
  .gitignore
  td.server/README.md
  td.vue/src/components/ProviderLoginButton.vue
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/main.desktop.js
  td.vue/src/router/desktop.js
  td.vue/src/router/index.js
  td.vue/src/service/provider/desktop.provider.js
  td.vue/src/service/provider/providerTypes.js
  td.vue/src/service/provider/providers.js
  td.vue/src/store/modules/auth.js
  td.vue/src/store/modules/provider.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/HomePage.vue
  td.vue/src/views/NewThreatModel.vue
  td.vue/tests/unit/router/desktop.spec.js
  td.vue/tests/unit/service/api/threatmodelApi.spec.js
  td.vue/tests/unit/service/provider/desktop.provider.spec.js
  td.vue/tests/unit/store/modules/branch.spec.js
  td.vue/tests/unit/store/modules/repository.spec.js
  td.vue/tests/unit/views/repositoryAccess.spec.js
Labels: bug, blocker, desktop, priority

#707 sort diagrams alphanumerically in report
  td.vue/src/service/provider/providers.js
  td.vue/src/store/modules/provider.js
  td.vue/src/views/ReportModel.vue
Labels: enhancement, reports

#708 bugfix for report crash on empty diagram
  td.vue/src/views/ThreatModelEdit.vue
Labels: bug, reports
