Repository OWASP/threat-dragon, pull requests merged in 2023-11, with the labels that each got.

#777 Update el.js
  td.vue/src/desktop/menu.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
Labels: bug, I18N, version-2.2

#779 Fix searchAsync to *actually* use the access_token (and pagination) correctly
  td.server/src/repositories/threatmodelrepository.js
Labels: bug, version-2.2

#788 update package versions for automation, server and frontend
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  package-lock.json
  package.json
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/styles/colors.scss
Labels: dependencies, automation

#789 Feature/plot4ai
  .gitignore
  package.json
  td.vue/src/assets/thumbnail.plot4ai.jpg
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/service/migration/cells.js
  td.vue/src/service/migration/data.js
  td.vue/src/service/threats/index.js
  td.vue/src/service/threats/models/index.js
  td.vue/src/service/threats/models/plot4ai.js
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/tests/unit/service/migration/data.spec.js
  td.vue/tests/unit/service/migration/diagram-extended.spec.js
  td.vue/tests/unit/service/threats/index.spec.js
  td.vue/tests/unit/service/threats/models/index.spec.js
  td.vue/tests/unit/service/threats/models/plot4ai.spec.js
Labels: enhancement, theat engine, version-2.2

#798 fix for #790
  td.vue/jest.config.js
  td.vue/package-lock.json
  td.vue/package.json
Labels: dependencies

#799 fix bug that overwrites node properties when adding dataflows
  td.vue/jest.config.js
  td.vue/src/components/GraphProperties.vue
  td.vue/src/service/x6/graph/data-changed.js
  td.vue/src/service/x6/graph/events.js
  td.vue/src/service/x6/shapes/index.js
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/tests/unit/service/x6/graph/events.spec.js
Labels: bug, blocker, priority, version-2.1

#787 feat: Adds Open Threat Modeling (OTM) support
  td.vue/src/components/Graph.vue
  td.vue/src/components/GraphButtons.vue
  td.vue/src/i18n/en.js
  td.vue/src/service/openThreatModel.js
  td.vue/src/service/save.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/ImportModel.vue
  td.vue/tests/unit/components/graph.spec.js
  td.vue/tests/unit/components/graphButtons.spec.js
  td.vue/tests/unit/service/openThreatModel.spec.js
  td.vue/tests/unit/service/save.spec.js
Labels: enhancement, version-2.2
