Repository OWASP/threat-dragon, pull requests merged in 2024-10, with the labels that each got.

#1095 Bundle of fixes for workflows and docs
  .github/workflows/browserstack.yaml
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  Dockerfile
  README.md
  docs/Gemfile.lock
  td.vue/package-lock.json
  td.vue/package.json
Labels: documentation, chore, automation

#1097 rearrange Zap test in pull requests
  .github/workflows/.trivyignore
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  td.vue/package.json
Labels: chore, automation

#1092 added google sign-in feature
  example.env
  package-lock.json
  td.server/package-lock.json
  td.server/package.json
  td.server/src/config/env.config.js
  td.server/src/config/routes.config.js
  td.server/src/controllers/configcontroller.js
  td.server/src/controllers/googleProviderThreatmodelController.js
  td.server/src/env/Google.js
  td.server/src/providers/google.js
  td.server/src/providers/index.js
  td.server/src/repositories/googledrive.js
  td.server/src/repositories/index.js
  td.server/test/config/routes.config.spec.js
  td.server/test/controllers/configcontroller.spec.js
  td.server/test/providers/google.spec.js
  td.server/test/providers/index.spec.js
  td.server/test/repositories/googledrive.spec.js
  td.vue/src/components/SelectionPage.vue
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/plugins/fontawesome-vue.js
  td.vue/src/router/google.js
  td.vue/src/router/index.js
  td.vue/src/service/api/googleDriveApi.js
  td.vue/src/service/provider/google.provider.js
  td.vue/src/service/provider/providerTypes.js
  td.vue/src/service/provider/providers.js
  td.vue/src/store/actions/folder.js
  td.vue/src/store/index.js
  td.vue/src/store/modules/folder.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/HomePage.vue
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/src/views/google/DriveAccess.vue
  td.vue/tests/unit/router/google.spec.js
  td.vue/tests/unit/service/api/googleDriveApi.spec.js
  td.vue/tests/unit/service/provider/google.provider.spec.js
  td.vue/tests/unit/store/actions/folder.spec.js
Labels: enhancement, multi-auth, version-2.3

#1111 Update BrowserStack platform and browser list
  td.vue/browserstack.nightly.json
  td.vue/browserstack.smokes.json
  td.vue/package-lock.json
  td.vue/package.json
Labels: chore, automation, version-2.3

#1099 Migrate to version 2.x antv/x6
  .gitignore
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/components/Graph.vue
  td.vue/src/components/GraphButtons.vue
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/GraphProperties.vue
  td.vue/src/components/ReadOnlyDiagram.vue
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/src/service/entity/default-properties.js
  td.vue/src/service/x6/graph/events.js
  td.vue/src/service/x6/graph/graph.js
  td.vue/src/service/x6/graph/keys.js
  td.vue/src/service/x6/ports.js
  td.vue/src/service/x6/shapes/actor.js
  td.vue/src/service/x6/shapes/flow-stencil.js
  td.vue/src/service/x6/shapes/flow.js
  td.vue/src/service/x6/shapes/process.js
  td.vue/src/service/x6/shapes/store.js
  td.vue/src/service/x6/shapes/text.js
  td.vue/src/service/x6/shapes/trust-boundary-box.js
  td.vue/src/service/x6/shapes/trust-boundary-curve-stencil.js
  td.vue/src/service/x6/shapes/trust-boundary-curve.js
  td.vue/src/service/x6/stencil.js
  td.vue/tests/unit/components/graph.spec.js
  td.vue/tests/unit/components/graphButtons.spec.js
  td.vue/tests/unit/components/readonlyDiagram.spec.js
  td.vue/tests/unit/entity/default-properties.spec.js
  td.vue/tests/unit/service/x6/factory.spec.js
  td.vue/tests/unit/service/x6/graph/events.spec.js
  td.vue/tests/unit/service/x6/graph/graph.spec.js
  td.vue/tests/unit/service/x6/graph/keys.spec.js
  td.vue/tests/unit/service/x6/shapes/flow-stencil.spec.js
  td.vue/tests/unit/service/x6/shapes/trust-boundary-curve-stencil.spec.js
  td.vue/tests/unit/service/x6/stencil.spec.js
Labels: version-2.3, AntV/X6

#1114 use File System Access API if supported on the browser
  td.vue/src/service/save.js
Labels: enhancement, version-2.3

#1086 Show element properties and out of scope reason in reports
  README.md
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/components/printed-report/ReportEntity.vue
  td.vue/src/components/report/DiagramDetail.vue
  td.vue/src/components/report/ReportEntity.vue
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/views/ReportModel.vue
  td.vue/tests/unit/components/printed-report/reportEntity.spec.js
  td.vue/tests/unit/components/report/reportEntity.spec.js
  td.vue/tests/unit/service/otm/OTMtoTD.spec.js
Labels: reports, version-2.3

#1120 fix for type/context errors
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/GraphThreats.vue
  td.vue/src/components/ThreatSuggestDialog.vue
  td.vue/src/service/migration/diagram.js
Labels: bug, version-2.3
