Repository OWASP/threat-dragon, pull requests merged in 2024-03, with the labels that each got.

#898 Fix:Buttons in Threat Edit Page
  td.vue/src/components/ThreatEditDialog.vue
Labels: enhancement, version-2.3

#896 delete stale pull requests
  .github/workflows/housekeeping.yaml
Labels: bug, automation

#900 add permissions to workflows
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
Labels: chore, automation

#909 Update el.js
  td.vue/src/i18n/el.js
Labels: enhancement, version-2.3

#914 Also build for arm64
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  release-process.md
Labels: enhancement, version-2.3

#910 Creation of threats made consistent
  td.vue/src/components/Graph.vue
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/GraphThreats.vue
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/service/threats/index.js
  td.vue/tests/unit/components/graph.spec.js
  td.vue/tests/unit/components/graphMeta.spec.js
  td.vue/tests/unit/components/graphThreats.spec.js
Labels: enhancement, version-2.3

#926 Update versions for workflow actions
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
Labels: chore, automation
