Repository OWASP/threat-dragon, pull requests merged in 2024-05, with the labels that each got.

#961 Revert "Bump rexml from 3.2.5 to 3.2.8 in /docs"
  docs/Gemfile.lock
Labels: bug

#959 Set model storage path via env var
  td.server/src/env/Bitbucket.js
  td.server/src/env/Github.js
  td.server/src/env/Gitlab.js
  td.server/src/env/ThreatDragon.js
  td.server/src/repositories/bitbucketrepo.js
  td.server/src/repositories/githubrepo.js
  td.server/src/repositories/gitlabrepo.js
  td.server/test/repositories/bitbucketrepo.spec.js
  td.server/test/repositories/gitlabrepo.spec.js
Labels: enhancement, version-2.3

#964 chore: upgrade SBOM generators
  .dockerignore
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  Dockerfile
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/vue.config.js
Labels: automation, version-2.3
