Repository OWASP/threat-dragon, pull requests merged in 2024-12, with the labels that each got.

#1138 Update actions/download-artifact to consistently use 4.1.8
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: automation, version-2.4

#1146 Add extra value for Priority field, and change default value
  Dockerfile
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/components/ThreatSuggestDialog.vue
  td.vue/src/components/report/ExecutiveSummary.vue
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/service/threats/index.js
  td.vue/tests/unit/service/threats/index.spec.js
Labels: enhancement, version-2.3.1

#1156 Update third party libraries
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release-snap.yaml
  .github/workflows/release-windows.yaml
  .github/workflows/release.yaml
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
Labels: automation
