Repository OWASP/threat-dragon, pull requests merged in 2024-02, with the labels that each got.

#849 enable multi selection of components
  td.vue/src/service/x6/graph/events.js
Labels: enhancement, version-2.2

#847 add schema verification for OTM
  .gitignore
  ThreatDragonModels/test/example-open-threat-model.json
  td.vue/src/assets/schema/open-threat-model-schema.js
  td.vue/src/assets/schema/threat-model-schema.V2.js
  td.vue/src/assets/schema/threat-model-schema.js
  td.vue/src/components/Graph.vue
  td.vue/src/main.desktop.js
  td.vue/src/service/ajv-SchemaVerification.js
  td.vue/src/service/openThreatModel.js
  td.vue/src/store/actions/threatmodel.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/ImportModel.vue
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/tests/unit/service/openThreatModel.spec.js
Labels: enhancement, version-2.2

#852 Prompt user to save model before quitting the app
  td.vue/public/preload.js
  td.vue/src/components/Graph.vue
  td.vue/src/desktop/desktop.js
  td.vue/src/desktop/menu.js
  td.vue/src/main.desktop.js
Labels: enhancement, version-2.2

#857 fix unit tests for td.vue
  .gitignore
  td.vue/public/preload.js
  td.vue/src/components/Graph.vue
  td.vue/src/desktop/desktop.js
  td.vue/src/desktop/menu.js
  td.vue/src/main.desktop.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/tests/unit/desktop/menu.spec.js
Labels: bug

#856 Fixes:Navbar
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/components/Navbar.vue
Labels: enhancement, version-2.2

#863 Fixes:Navbar Issues
  td.vue/src/i18n/hi.js
Labels: bug, enhancement, I18N, version-2.2

#865 Fixes:td.vue/src/i8n/hi.js
  td.vue/src/i18n/hi.js
Labels: enhancement, I18N, version-2.2

#870 #9 gitlab
  example.env
  td.server/package-lock.json
  td.server/package.json
  td.server/src/config/env.config.js
  td.server/src/controllers/configcontroller.js
  td.server/src/env/Gitlab.js
  td.server/src/providers/gitlab.js
  td.server/src/providers/index.js
  td.server/src/repositories/gitlabrepo.js
  td.server/src/repositories/index.js
  td.server/test/controllers/configcontroller.spec.js
  td.server/test/providers/gitlab.spec.js
  td.server/test/repositories/gitlabrepo.spec.js
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/plugins/fontawesome-vue.js
  td.vue/src/service/provider/gitlab.provider.js
  td.vue/src/service/provider/providers.js
  td.vue/src/store/modules/config.js
  td.vue/src/views/HomePage.vue
Labels: multi-auth, priority, version-2.2

#868 Fixes:Homepage
  td.vue/src/views/HomePage.vue
  td.vue/tests/unit/views/homePage.spec.js
Labels: enhancement, version-2.2

#874 Desktop: prompt user before downloading auto updates
  td.vue/src/desktop/desktop.js
  td.vue/src/service/provider/providers.js
  td.vue/src/service/schema/ajv.js
Labels: enhancement, desktop, version-2.2

#876 Fixes:dashboard action
  td.vue/src/components/DashboardAction.vue
Labels: enhancement, version-2.2

#888 remove desktop splash screen
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  .gitignore
  .trivyignore
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/public/desktop-loading.html
  td.vue/src/desktop/desktop.html
  td.vue/src/desktop/desktop.js
  td.vue/src/styles/bootstrap-theme.css
  td.vue/tests/e2e/desktop/desktop.spec.js
Labels: desktop, version-2.3
