Repository OWASP/threat-dragon, pull requests merged in 2024-07, with the labels that each got.

#996 Aligned scope param default value with oauth spec
  td.server/src/providers/gitlab.js
Labels: bug, multi-auth, version-2.3

#988 [Feature]: Threat type suggestion
  td.server/src/providers/gitlab.js
  td.server/src/repositories/gitlabrepo.js
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/service/threats/index.js
  td.vue/src/service/threats/models/index.js
  td.vue/tests/unit/components/threatEditDialog.spec.js
Labels: documentation, enhancement, discussion, pending-release, API, GSoC, version-2.3, javascript

#997 update pipeline dependencies
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  td.vue/package-lock.json
  td.vue/package.json
Labels: chore, automation

#1000 fix: debug log displays objects properly
  td.server/src/controllers/auth.js
  td.server/src/controllers/threatmodelcontroller.js
Labels: bug, version-2.3

#1004 do not scare the users with version 1.x warnings
  td.server/src/repositories/gitlabrepo.js
  td.vue/src/App.vue
  td.vue/src/service/migration/diagram.js
  td.vue/src/service/schema/ajv.js
  td.vue/tests/e2e/support/e2e.js
  td.vue/tests/unit/app.spec.js
Labels: enhancement, version-2.3

#1008 build for MacOS arm64 target
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  Dockerfile
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/tests/unit/components/graph.spec.js
  td.vue/tests/unit/components/graphButtons.spec.js
  td.vue/tests/unit/service/debounce.spec.js
  td.vue/tests/unit/service/x6/graph/events.spec.js
  td.vue/tests/unit/service/x6/stencil.spec.js
  td.vue/tests/unit/store/modules/branch.spec.js
  td.vue/tests/unit/store/modules/cell.spec.js
  td.vue/tests/unit/store/modules/provider.spec.js
  td.vue/tests/unit/store/modules/repository.spec.js
  td.vue/tests/unit/store/modules/threatmodel.spec.js
  td.vue/tests/unit/views/homePage.spec.js
  td.vue/vue.config.js
Labels: enhancement, automation, version-2.3

#1013 Fixes for workflow docker builds
  .github/workflows/browserstack.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: bug, version-2.3

#1011 fix: logger can handle circular objects
  td.server/src/controllers/auth.js
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/helpers/logger.helper.js
  td.server/test/helpers/logger.helper.spec.js
Labels: bug, version-2.3

#1014 fix: REPO_SEARCH envs are processed by the application
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/env/Github.js
  td.server/src/env/ThreatDragon.js
  td.server/test/env/ThreatDragon.spec.js
Labels: bug, version-2.3

#1015 Encode url params to handle deeply nested repositories
  td.vue/src/service/api/threatmodelApi.js
  td.vue/tests/unit/service/api/threatmodelApi.spec.js
Labels: bug, version-2.3

#1017 backward compatible for env vars GITHUB_USE_SEARCH and GITHUB_SEARCH_QUERY
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .gitignore
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/env/Bitbucket.js
  td.server/src/env/Github.js
  td.server/src/env/Gitlab.js
  td.server/test/controllers/healthz.spec.js
  td.server/test/env/Bitbucket.spec.js
  td.server/test/env/Github.spec.js
  td.server/test/env/Gitlab.spec.js
  td.server/test/env/ThreatDragon.spec.js
Labels: chore, version-2.3

#1025 correct pdf extension when saving file
  td.vue/src/desktop/menu.js
Labels: bug, desktop, version-2.3

#1026 desktop recent file sub-menu only for MacOS
  .github/workflows/browserstack.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  td.vue/src/desktop/menu.js
  td.vue/tests/unit/desktop/menu.spec.js
Labels: bug, desktop, version-2.3

#1029 provide separator for contributor tags
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/views/ThreatModelEdit.vue
Labels: enhancement, version-2.3

#1038 Add example TMBOMs
  ThreatDragonModels/tmbom-example.cdx.json
  ThreatDragonModels/tmbom-otm-example.cdx.json
Labels: enhancement, version-3.x

#1039 Update zh.js
  td.vue/src/i18n/zh.js
Labels: I18N, version-2.3

#1040 update workflows for versions and staleness
  .github/workflows/.zap-rules-web.tsv
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  td.server/package-lock.json
  td.server/package.json
  td.server/src/app.js
Labels: chore, automation
