Repository OWASP/threat-dragon, pull requests merged in 2024-01, with the labels that each got.

#822 made language selection understandable
  td.vue/src/components/LocaleSelect.vue
  td.vue/tests/unit/components/localeSelect.spec.js
Labels: enhancement, version-2.1

#825 fixed graph container resizing issue
  td.vue/src/components/Graph.vue
Labels: enhancement, version-2.2

#821 Desktop diagram save
  ThreatDragonModels/test-reports.json
  td.vue/public/preload.js
  td.vue/src/components/Graph.vue
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/desktop/desktop.js
  td.vue/src/desktop/menu.js
  td.vue/src/main.desktop.js
  td.vue/src/service/migration/diagram.js
  td.vue/src/store/actions/cell.js
  td.vue/src/store/actions/threatmodel.js
  td.vue/src/store/modules/threatmodel.js
  td.vue/src/views/ImportModel.vue
  td.vue/src/views/ReportModel.vue
  td.vue/src/views/ThreatModel.vue
  td.vue/src/views/ThreatModelEdit.vue
  td.vue/src/views/git/ThreatModelSelect.vue
  td.vue/tests/unit/components/graph.spec.js
  td.vue/tests/unit/desktop/menu.spec.js
  td.vue/tests/unit/service/migration/diagram.spec.js
  td.vue/tests/unit/store/actions/threatmodel.spec.js
  td.vue/tests/unit/store/modules/threatmodel.spec.js
  td.vue/tests/unit/views/threatmodelEdit.spec.js
Labels: bug, version-2.2

#831 update github workflow actions
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/components/LocaleSelect.vue
Labels: chore, automation

#832 add indication that model has been saved
  ThreatDragonModels/test-reports.json
  td.vue/src/store/modules/threatmodel.js
Labels: enhancement, version-2.2

#836 Navbar fixed
  ThreatDragonModels/demo-threat-model.json
  td.vue/src/components/Navbar.vue
Labels: enhancement

#833 Added schema verification while importing model
  td.vue/src/assets/threat-model-schema.V2.js
  td.vue/src/assets/threat-model-schema.js
  td.vue/src/service/ajv-SchemaVerification.js
  td.vue/src/views/ImportModel.vue
Labels: enhancement, version-2.2

#842 Added a loading screen before initialization
  td.vue/src/desktop/desktop.js
  utils/Desktop-Loader/loading.html
Labels: enhancement, version-2.2

#843 Update loader and workfows
  .github/workflows/browserstack.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  ThreatDragonModels/test/example-open-threat-model.json
  ThreatDragonModels/test/malformed-new-model.json
  ThreatDragonModels/test/test-reports.json
  ThreatDragonModels/test/v2-malformed-new-model.json
  td.vue/babel.config.js
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/public/desktop-loading.html
  td.vue/src/desktop/desktop.js
  td.vue/tests/e2e/desktop/desktop.spec.js
Labels: chore, version-2.2
