Repository OWASP/threat-dragon, pull requests merged in 2024-06, with the labels that each got.

#966 ci: fix docker SBOM gathering
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: bug, automation, version-2.3

#965 Support Custom Gitlab Instance
  td.server/src/env/Gitlab.js
  td.server/src/providers/gitlab.js
  td.server/src/repositories/gitlabrepo.js
Labels: enhancement, version-2.3

#971 various updates to the workflows
  .github/workflows/.zap-rules-web.tsv
  .github/workflows/browserstack.yaml
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/i18n/ja.js
  td.vue/tests/e2e/desktop/desktop.spec.js
  td.vue/wdio.config.js
Labels: chore, automation

#974 Heroku-deploy action in CI pipeline
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  .trivyignore
  Dockerfile
  package-lock.json
  package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/wdio.config.js
Labels: chore, automation, version-2.3
