Repository OWASP/threat-dragon, pull requests merged in 2024-08, with the labels that each got.

#1045 allow access for css
  .github/workflows/.zap-rules-web.tsv
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  ThreatDragonModels/tmbom-pytm-example.cdx.json
  td.server/package-lock.json
  td.server/package.json
  td.server/src/app.js
  td.vue/package.json
  td.vue/src/service/x6/graph/events.js
Labels: bug, blocker, priority

#1047 Change vertices properties from integer to number so they can be imported
  td.vue/src/service/schema/threat-model-schema.V2.js
Labels: bug, blocker, priority, version-2.3

#1048 remove outdated utilities
  utils/DragonExtractor/DragonThreatExtractor.js
  utils/DragonExtractor/README.md
  utils/DragonExtractor/runtest.sh
  utils/TMT2TD/README.md
  utils/TMT2TD/Sample_Threat_Model.tm7
  utils/TMT2TD/TMT2TD.py
  utils/TMT2TD/Transpiled_Sample_Threat_Model.json
  utils/threat-mvp/Dockerfile
  utils/threat-mvp/Jira_API.txt
  utils/threat-mvp/README.md
  utils/threat-mvp/config.ini
  utils/threat-mvp/git_party_integration.py
  utils/threat-mvp/itmj.py
  utils/threat-mvp/logger.py
  utils/threat-mvp/mail.py
  utils/threat-mvp/parse_json_td.py
  utils/threat-mvp/read_json_td.py
  utils/threat-mvp/td_json/first_tm.json
  utils/threat-mvp/td_json/test1.json
  utils/threat-mvp/third_party_integration.py
Labels: chore, version-2.3

#1053 [Reinstated]: Threat by context
  td.vue/src/components/GraphMeta.vue
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/components/ThreatSuggestDialog.vue
  td.vue/src/service/threats/oats/context-generator.js
Labels: documentation, enhancement, pending-release, GSoC, version-2.3, javascript
