Repository OWASP/threat-dragon, pull requests merged in 2024-04, with the labels that each got.

#933 i18n: Add Japanese translation
  td.vue/src/components/LocaleSelect.vue
  td.vue/src/desktop/menu.js
  td.vue/src/i18n/index.js
  td.vue/src/i18n/ja.js
  td.vue/tests/unit/components/localeSelect.spec.js
Labels: I18N, version-2.3

#934 update third party packages
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/tests/unit/components/localeSelect.spec.js
Labels: chore

#940 update cupcake SVGs to handle light and dark modes
  td.vue/src/assets/threatdragon_logo.svg
  td.vue/src/assets/threatdragon_logo_image.svg
Labels: enhancement, version-2.3

#942 Stop report options moving and obscuring language drop-down
  td.vue/src/views/ReportModel.vue
Labels: bug, version-2.3

#951 Fix typos in demo threat descriptions
  ThreatDragonModels/demo-threat-model.json
  ThreatDragonModels/v2-threat-model.json
  td.vue/src/service/demo/demo-threat-model.js
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/tests/e2e/fixtures/v1-model.json
Labels: enhancement, version-2.3

#952 Fix undo for edges
  td.vue/src/service/x6/shapes/index.js
Labels: bug, version-2.3

#943 update versions for workflow actions
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  .gitignore
  release-process.md
  td.vue/e2e.local.config.js
  td.vue/e2e.smokes.ci.config.js
  td.vue/e2e.smokes.config.js
  td.vue/e2e.smokes.local.config.js
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/components/Navbar.vue
  td.vue/src/store/modules/provider.js
  td.vue/src/views/HomePage.vue
  td.vue/tests/e2e/desktop/desktop.spec.js
  td.vue/tests/e2e/specs/smokes/edit.cy.js
  td.vue/tests/e2e/specs/smokes/smokes.cy.js
  td.vue/tests/e2e/specs/threatmodel/edit.cy.js
  td.vue/tests/e2e/support/e2e.js
  td.vue/wdio.config.js
Labels: chore
