Repository OWASP/threat-dragon, pull requests merged in 2025-03, with the labels that each got.

#1222 Fixing label issue for flows and boundary curves
  td.vue/src/service/x6/graph/events.js
  td.vue/src/service/x6/shapes/flow.js
  td.vue/src/service/x6/shapes/trust-boundary-curve.js
Labels: bug, priority, version-2.4, AntV/X6

#1223 Rename "PORT" environment variable to "SERVER_API_PORT"
  td.vue/vue.config.js
Labels: enhancement, version-2.4

#1233 Bug fix for unexpected label on Trust Boundary Box
  .lycheeignore
  td.vue/src/service/x6/shapes/trust-boundary-box.js
Labels: bug, priority, AntV/X6, version-2.4.1

#1232 Bug fix for data flows and trust boundary curve labels incorrectly displayed
  td.vue/src/service/x6/shapes/flow.js
  td.vue/src/service/x6/shapes/trust-boundary-curve.js
Labels: bug, priority, AntV/X6, version-2.4.1

#1236 priority level TBD instead of TBA
  td.vue/src/components/ThreatEditDialog.vue
  td.vue/src/components/ThreatSuggestDialog.vue
  td.vue/src/components/report/ExecutiveSummary.vue
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/service/threats/index.js
  td.vue/tests/unit/service/threats/index.spec.js
Labels: enhancement, version-2.4.1

#1237 Revert: Clean up, add error checking, remove ambiguity around term "port"
  example.env
  td.server/src/app.js
  td.server/src/env/ThreatDragon.js
  td.server/src/healthcheck.js
  td.server/test/env/ThreatDragon.spec.js
  td.vue/vue.config.js
Labels: priority, version-2.4.1

#1239 Add demo models from Threat Model Cookbook
  .gitignore
  td.vue/src/service/demo/cryptocurrency-wallet.js
  td.vue/src/service/demo/cryptocurrency-wallet.json
  td.vue/src/service/demo/generic-cms.js
  td.vue/src/service/demo/generic-cms.json
  td.vue/src/service/demo/index.js
  td.vue/src/service/demo/iot-device.js
  td.vue/src/service/demo/iot-device.json
  td.vue/src/service/demo/online-game.js
  td.vue/src/service/demo/online-game.json
  td.vue/src/service/demo/payment-online.js
  td.vue/src/service/demo/payment-online.json
  td.vue/src/service/demo/payment.js
  td.vue/src/service/demo/renting-car.json
  td.vue/src/service/demo/three-tier-web-app.json
  td.vue/src/service/demo/v2-new-model.json
  td.vue/src/service/demo/v2-threat-model.js
  td.vue/src/service/demo/v2-threat-model.json
  td.vue/src/store/modules/threatmodel.js
  td.vue/tests/unit/views/demo/selectDemoModel.spec.js
Labels: enhancement, version-2.5

#1241 Various minor updates, notably lint now maximally strict
  .github/pull_request_template.md
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  README.md
  contributing.md
  release-process.md
  td.server/.eslintrc.js
  td.server/package-lock.json
  td.server/package.json
  td.vue/.eslintrc.js
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/tests/e2e/.eslintrc.js
Labels: chore, version-2.5

#1250 Update workflow actions
  .github/workflows/browserstack.yaml
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release-snap.yaml
  .github/workflows/release-windows.yaml
  .github/workflows/release.yaml
  td.vue/README.md
Labels: chore, automation
