Repository OWASP/threat-dragon, pull requests merged in 2025-01, with the labels that each got.

#1166 update deps in workflow pipelines
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release-snap.yaml
  .github/workflows/release-windows.yaml
  .github/workflows/release.yaml
Labels: dependencies, chore, automation

#1170 Update model file version
  td.vue/src/service/migration/diagram.js
  td.vue/src/store/modules/threatmodel.js
Labels: enhancement, version-2.3.1

#1171 Both diagram description and icon in threat model view
  td.vue/src/views/ThreatModel.vue
Labels: enhancement, version-2.3.1

#1178 fix broken repository search
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/repositories/bitbucketrepo.js
  td.server/src/repositories/githubrepo.js
  td.server/src/repositories/gitlabrepo.js
  td.vue/src/components/SelectionPage.vue
  td.vue/src/service/api/threatmodelApi.js
  td.vue/src/store/modules/repository.js
  td.vue/src/views/git/BranchAccess.vue
  td.vue/src/views/git/RepositoryAccess.vue
  td.vue/tests/unit/service/api/threatmodelApi.spec.js
Labels: bug, version-2.3.1

#1181 Feat: Add dialog for creating branches and indicators for protected branches
  td.server/src/config/routes.config.js
  td.server/src/controllers/threatmodelcontroller.js
  td.server/src/repositories/bitbucketrepo.js
  td.server/src/repositories/githubrepo.js
  td.server/src/repositories/gitlabrepo.js
  td.server/test/repositories/bitbucketrepo.spec.js
  td.server/test/repositories/githubrepo.spec.js
  td.server/test/repositories/gitlabrepo.spec.js
  td.vue/src/components/AddBranchDialog.vue
  td.vue/src/components/SelectionPage.vue
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/plugins/fontawesome-vue.js
  td.vue/src/service/api/threatmodelApi.js
  td.vue/src/store/actions/branch.js
  td.vue/src/store/modules/branch.js
  td.vue/src/views/git/BranchAccess.vue
  td.vue/tests/unit/components/addBranchDialog.spec.js
  td.vue/tests/unit/components/selectionPage.spec.js
  td.vue/tests/unit/views/branchAccess.spec.js
Labels: enhancement, version-2.3.1
