Repository OWASP/threat-dragon, pull requests merged in 2025-02, with the labels that each got.

#1184 Fix id duplication on ThreatSuggestDialog
  td.vue/src/components/ThreatSuggestDialog.vue
Labels: bug, version-2.3.1

#1187 add tls support issue #1158
  example.env
  td.vue/package.json
  td.vue/vue.config.js
Labels: enhancement, version-2.4

#1192 Add Graph Export to PNG, SVG, JPEG
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/components/GraphButtons.vue
  td.vue/src/i18n/en.js
  td.vue/src/service/x6/graph/graph.js
  td.vue/src/service/x6/shapes/flow.js
  td.vue/src/service/x6/shapes/trust-boundary-curve.js
  td.vue/tests/unit/components/graphButtons.spec.js
  td.vue/tests/unit/service/x6/graph/graph.spec.js
Labels: enhancement, version-2.4

#1194 Added search functionality for language selection dropdown
  td.vue/src/components/LocaleSelect.vue
Labels: enhancement, version-2.4

#1196 provide locale name in locale display
  td.vue/src/components/LocaleSelect.vue
  td.vue/tests/unit/components/localeSelect.spec.js
Labels: enhancement, version-2.4

#1195 Reinstate the label text for trust boundary boxes
  .github/workflows/.trivyignore
  td.vue/src/service/x6/shapes/actor.js
  td.vue/src/service/x6/shapes/trust-boundary-box.js
  td.vue/tests/unit/service/x6/shapes/trust-boundary-box.spec.js
Labels: bug, version-2.4, AntV/X6

#1201 reinstate diagram node resizing
  td.vue/src/service/x6/graph/graph.js
Labels: bug, version-2.4

#1197 clean up console of warnings and errors
  td.vue/jest.config.js
  td.vue/package-lock.json
  td.vue/package.json
  td.vue/src/service/migration/diagram.js
  td.vue/vue.config.js
Labels: bug, version-2.4

#1206 consolidating hostname variable
  example.env
  td.vue/vue.config.js
Labels: enhancement, version-2.4

#1205 Make edge labels legible and selectable
  td.vue/src/service/demo/v2-new-model.js
  td.vue/src/service/x6/graph/data-changed.js
  td.vue/src/service/x6/graph/events.js
  td.vue/src/service/x6/shapes/flow-stencil.js
  td.vue/src/service/x6/shapes/flow.js
  td.vue/src/service/x6/shapes/trust-boundary-curve-stencil.js
  td.vue/src/service/x6/shapes/trust-boundary-curve.js
  td.vue/src/views/git/ThreatModelSelect.vue
  td.vue/tests/unit/service/x6/graph/events.spec.js
Labels: bug, priority, version-2.4, AntV/X6

#1208 Update dependencies in workflows, front-end and server
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  td.server/package-lock.json
  td.server/package.json
  td.vue/package-lock.json
  td.vue/package.json
Labels: dependencies, automation, version-2.4

#1214 provide confirmation that save has taken place
  td.vue/src/store/modules/threatmodel.js
Labels: bug, version-2.4

#1220 update workflows for latest versions of actions
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
Labels: dependencies, chore, automation
