Repository OWASP/threat-dragon, pull requests merged in 2025-05, with the labels that each got.

#1270 GitLab docs consistent
  .github/workflows/pull_request.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  docs/configure/bitbucket.md
  docs/configure/github.md
  docs/configure/gitlab.md
  docs/configure/google.md
Labels: documentation, automation

#1271 apply checks to docs on pull requests
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .release-note-template.md
  .wordlist.txt
  README.md
  docs/CNAME
  docs/README.md
  release-process.md
Labels: automation

#1273 Add about box for all platforms
  .github/workflows/housekeeping.yaml
  .github/workflows/pull_request.yaml
  .lycheeignore
  td.vue/src/desktop/menu.js
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/tests/unit/desktop/menu.spec.js
Labels: enhancement, version-2.5

#1288 Update el.js
  td.vue/src/i18n/el.js
Labels: I18N, version-2.5

#1285 Multiple Diagrams: copy diagrams from edit page
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/src/plugins/fontawesome-vue.js
  td.vue/src/views/ThreatModelEdit.vue
Labels: enhancement, version-2.5

#1291 Report: list Open and Not Applicable threats separately
  td.vue/src/components/printed-report/ExecutiveSummary.vue
  td.vue/src/components/printed-report/ReportEntity.vue
  td.vue/src/components/report/ExecutiveSummary.vue
  td.vue/src/components/report/ReportEntity.vue
  td.vue/src/i18n/ar.js
  td.vue/src/i18n/de.js
  td.vue/src/i18n/el.js
  td.vue/src/i18n/en.js
  td.vue/src/i18n/es.js
  td.vue/src/i18n/fi.js
  td.vue/src/i18n/fr.js
  td.vue/src/i18n/hi.js
  td.vue/src/i18n/id.js
  td.vue/src/i18n/ja.js
  td.vue/src/i18n/ms.js
  td.vue/src/i18n/pt.js
  td.vue/src/i18n/ru.js
  td.vue/src/i18n/uk.js
  td.vue/src/i18n/zh.js
  td.vue/tests/e2e/specs/threatmodel/report.cy.js
  td.vue/tests/unit/components/printed-report/executiveSummary.spec.js
  td.vue/tests/unit/components/printed-report/reportEntity.spec.js
  td.vue/tests/unit/components/report/executiveSummary.spec.js
  td.vue/tests/unit/components/report/reportEntity.spec.js
Labels: bug, version-2.5
